name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build -t docker.io/${{ secrets.DOCKERHUB_USERNAME }}/gcc-arm-toolchain:latest .

      - name: Push the Docker image
        run: |
          docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/gcc-arm-toolchain:latest
